// Generated by tools/seed_from_xlsx.py from 'Lifting Tracker.xlsx'.
// Loaded once, on first run, when localStorage is empty.
export const SEED = {
  "exercises": [
    {
      "id": "squat",
      "name": "Squat",
      "step": 2.5,
      "base": 0.0,
      "gainPerWeek": 0.0075,
      "setsPerSession": 5.0,
      "setsPerWeek": 15.0,
      "notes": ""
    },
    {
      "id": "bench-press",
      "name": "Bench Press",
      "step": 2.5,
      "base": 0.0,
      "gainPerWeek": 0.005,
      "setsPerSession": 5.0,
      "setsPerWeek": 15.0,
      "notes": ""
    },
    {
      "id": "deadlift",
      "name": "Deadlift",
      "step": 5.0,
      "base": 0.0,
      "gainPerWeek": 0.0075,
      "setsPerSession": 5.0,
      "setsPerWeek": 15.0,
      "notes": ""
    },
    {
      "id": "overhead-press",
      "name": "Overhead Press",
      "step": 2.5,
      "base": 0.0,
      "gainPerWeek": 0.005,
      "setsPerSession": 5.0,
      "setsPerWeek": 15.0,
      "notes": ""
    },
    {
      "id": "seated-row",
      "name": "Seated row",
      "step": 2.3,
      "base": 0.0,
      "gainPerWeek": 0.006,
      "setsPerSession": 5.0,
      "setsPerWeek": 15.0,
      "notes": ""
    },
    {
      "id": "lat-pulldown",
      "name": "Lat pulldown",
      "step": 2.3,
      "base": 0.0,
      "gainPerWeek": 0.005,
      "setsPerSession": 5.0,
      "setsPerWeek": 15.0,
      "notes": ""
    },
    {
      "id": "bicep-curl",
      "name": "Bicep curl",
      "step": 2.5,
      "base": 0.0,
      "gainPerWeek": 0.005,
      "setsPerSession": 5.0,
      "setsPerWeek": 15.0,
      "notes": ""
    }
  ],
  "entries": [
    {
      "id": "seed-4",
      "date": "2026-08-13",
      "exerciseId": "squat",
      "weight": 80.0,
      "reps": 5.0,
      "sets": 3.0,
      "rir": 1.0,
      "notes": "",
      "seq": 4
    },
    {
      "id": "seed-6",
      "date": "2026-08-13",
      "exerciseId": "deadlift",
      "weight": 100.0,
      "reps": 8.0,
      "sets": 3.0,
      "rir": 5.0,
      "notes": "",
      "seq": 6
    },
    {
      "id": "seed-3",
      "date": "2026-08-15",
      "exerciseId": "bench-press",
      "weight": 65.0,
      "reps": 5.0,
      "sets": 4.0,
      "rir": 1.0,
      "notes": "",
      "seq": 3
    },
    {
      "id": "seed-5",
      "date": "2026-08-15",
      "exerciseId": "overhead-press",
      "weight": 30.0,
      "reps": 5.0,
      "sets": 2.0,
      "rir": 1.0,
      "notes": "",
      "seq": 5
    },
    {
      "id": "seed-7",
      "date": "2026-08-15",
      "exerciseId": "bicep-curl",
      "weight": 32.0,
      "reps": 8.0,
      "sets": 3.0,
      "rir": 0.0,
      "notes": "",
      "seq": 7
    },
    {
      "id": "seed-8",
      "date": "2026-08-16",
      "exerciseId": "lat-pulldown",
      "weight": 66.0,
      "reps": 8.0,
      "sets": 3.0,
      "rir": 0.0,
      "notes": "",
      "seq": 8
    },
    {
      "id": "seed-9",
      "date": "2026-08-16",
      "exerciseId": "seated-row",
      "weight": 59.0,
      "reps": 8.0,
      "sets": 4.0,
      "rir": 0.0,
      "notes": "",
      "seq": 9
    },
    {
      "id": "seed-10",
      "date": "2026-08-16",
      "exerciseId": "squat",
      "weight": 80.0,
      "reps": 5.0,
      "sets": 5.0,
      "rir": 0.0,
      "notes": "",
      "seq": 10
    },
    {
      "id": "seed-11",
      "date": "2026-08-16",
      "exerciseId": "deadlift",
      "weight": 100.0,
      "reps": 8.0,
      "sets": 4.0,
      "rir": 0.0,
      "notes": "",
      "seq": 11
    },
    {
      "id": "seed-12",
      "date": "2026-08-17",
      "exerciseId": "bench-press",
      "weight": 65.0,
      "reps": 5.0,
      "sets": 5.0,
      "rir": 0.0,
      "notes": "",
      "seq": 12
    },
    {
      "id": "seed-13",
      "date": "2026-08-17",
      "exerciseId": "overhead-press",
      "weight": 30.0,
      "reps": 5.0,
      "sets": 3.0,
      "rir": 0.0,
      "notes": "",
      "seq": 13
    },
    {
      "id": "seed-14",
      "date": "2026-08-17",
      "exerciseId": "bicep-curl",
      "weight": 31.5,
      "reps": 4.0,
      "sets": 6.0,
      "rir": 0.0,
      "notes": "",
      "seq": 14
    }
  ],
  "settings": {
    "formula": "epley",
    "setBonusK": 0.05,
    "lookbackDays": 84,
    "defaultStep": 2.5,
    "defaultGainPerWeek": 0.0075,
    "unit": "kg",
    "idealBand": 0.01,
    "stretchBand": 0.03
  }
};
