#!/usr/bin/env python3
"""Regenerate js/seed.js from 'Lifting Tracker.xlsx'.

Reads the Exercises, Log and Settings sheets and writes the first-run seed the
app loads when localStorage is empty. Run it again if you edit the spreadsheet:

    python3 tools/seed_from_xlsx.py
"""
import json
import os
import re
import sys

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is required:  python3 -m pip install openpyxl")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
XLSX = os.path.join(ROOT, "Lifting Tracker.xlsx")
OUT = os.path.join(ROOT, "js", "seed.js")


def slug(name):
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s or "exercise"


def num(v, default=None):
    return float(v) if isinstance(v, (int, float)) else default


def main():
    include_log = "--no-log" not in sys.argv
    if not os.path.exists(XLSX):
        sys.exit(
            f"Could not find {os.path.basename(XLSX)} in {ROOT}.\n"
            "The app does not need it — everything it held is already in js/seed.js —\n"
            "but re-importing does. Put the workbook back beside this project to run this."
        )
    wb = openpyxl.load_workbook(XLSX, data_only=True)

    # ---- Settings -------------------------------------------------------
    st = wb["Settings"]
    settings = {
        "formula": "brzycki" if num(st["B4"].value, 1) == 2 else "epley",
        "setBonusK": num(st["B5"].value, 0.05),
        "lookbackDays": int(num(st["B6"].value, 84)),
        "defaultStep": num(st["B7"].value, 2.5),
        "defaultGainPerWeek": num(st["B8"].value, 0.0075),
        "unit": "kg",
    }

    ns = wb["NextSession"]
    settings["idealBand"] = num(ns["I23"].value, 0.01)
    settings["stretchBand"] = num(ns["I24"].value, 0.03)

    # ---- Exercises ------------------------------------------------------
    ex_sheet = wb["Exercises"]
    exercises, by_name = [], {}
    for row in range(2, 17):
        name = ex_sheet.cell(row=row, column=1).value
        if not isinstance(name, str) or not name.strip():
            continue
        name = name.strip()
        # Column G is optional: add a "Starting weight" header there and the
        # importer will pick it up. Absent, the lift starts at 0 (fully loadable).
        ex = {
            "id": slug(name),
            "name": name,
            "step": num(ex_sheet.cell(row=row, column=2).value, settings["defaultStep"]),
            "base": max(0.0, num(ex_sheet.cell(row=row, column=7).value, 0.0)),
            "gainPerWeek": num(ex_sheet.cell(row=row, column=3).value, settings["defaultGainPerWeek"]),
            "setsPerSession": num(ex_sheet.cell(row=row, column=4).value, 3),
            "setsPerWeek": num(ex_sheet.cell(row=row, column=5).value, 15),
            "notes": (ex_sheet.cell(row=row, column=6).value or ""),
        }
        exercises.append(ex)
        by_name[name.lower()] = ex["id"]

    # ---- Log ------------------------------------------------------------
    log_sheet = wb["Log"]
    entries = []
    for row in range(3, log_sheet.max_row + 1):
        date = log_sheet.cell(row=row, column=1).value
        name = log_sheet.cell(row=row, column=2).value
        weight = num(log_sheet.cell(row=row, column=3).value)
        reps = num(log_sheet.cell(row=row, column=4).value)
        if date is None or not isinstance(name, str) or weight is None or reps is None:
            continue
        ex_id = by_name.get(name.strip().lower())
        if ex_id is None:                      # a lift logged but never set up
            ex_id = slug(name)
            exercises.append({
                "id": ex_id, "name": name.strip(), "step": settings["defaultStep"],
                "base": 0.0, "gainPerWeek": settings["defaultGainPerWeek"],
                "setsPerSession": 3, "setsPerWeek": 15, "notes": "",
            })
            by_name[name.strip().lower()] = ex_id
        rir = num(log_sheet.cell(row=row, column=6).value)
        entries.append({
            "id": f"seed-{row}",
            "date": date.strftime("%Y-%m-%d"),
            "exerciseId": ex_id,
            "weight": weight,
            "reps": reps,
            "sets": num(log_sheet.cell(row=row, column=5).value, 1),
            "rir": rir,
            "notes": log_sheet.cell(row=row, column=7).value or "",
            "seq": row,                        # preserves spreadsheet row order
        })

    entries.sort(key=lambda e: (e["date"], e["seq"]))
    if not include_log:
        entries = []
    seed = {"exercises": exercises, "entries": entries, "settings": settings}

    with open(OUT, "w") as fh:
        fh.write("// Generated by tools/seed_from_xlsx.py from 'Lifting Tracker.xlsx'.\n")
        fh.write("// Loaded once, on first run, when localStorage is empty.\n")
        fh.write("export const SEED = ")
        json.dump(seed, fh, indent=2)
        fh.write(";\n")

    print(f"wrote {OUT}")
    print(f"  {len(exercises)} exercises, {len(entries)} log entries")
    print(f"  settings: {settings}")


if __name__ == "__main__":
    main()
